"""career_data_model_restructure

Revision ID: 6c3da8c67690
Revises: 20260415_01
Create Date: 2026-04-15 23:20:57.368909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c3da8c67690'
down_revision: Union[str, None] = '20260415_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_profiles',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=False),
    sa.Column('portfolio_url', sa.String(length=500), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('professional_summary', sa.Text(), nullable=False),
    sa.Column('skill_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_profiles_user_id'), 'career_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_career_profiles_workspace_id'), 'career_profiles', ['workspace_id'], unique=False)
    op.create_table('work_experiences',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_url', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('role_title', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experiences_profile_id'), 'work_experiences', ['profile_id'], unique=False)
    op.create_table('projects',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('work_experience_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_experience_id'], ['work_experiences.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_profile_id'), 'projects', ['profile_id'], unique=False)
    op.create_index(op.f('ix_projects_work_experience_id'), 'projects', ['work_experience_id'], unique=False)
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_workspace_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    # Drop old data — user confirmed no backward compatibility needed
    op.execute("DELETE FROM update_suggestions")
    op.execute("DELETE FROM achievement_resume_links")
    op.execute("DELETE FROM achievement_role_matches")
    op.execute("DELETE FROM agent_runs")
    op.execute("DELETE FROM achievements")
    op.add_column('achievements', sa.Column('profile_id', sa.UUID(), nullable=False))
    op.add_column('achievements', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('achievements', sa.Column('work_experience_id', sa.UUID(), nullable=True))
    op.add_column('achievements', sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('achievements', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('achievements', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('achievements', sa.Column('date_occurred', sa.Date(), nullable=True))
    op.alter_column('achievements', 'source_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_workspace_id'), table_name='achievements')
    op.create_index(op.f('ix_achievements_profile_id'), 'achievements', ['profile_id'], unique=False)
    op.create_index(op.f('ix_achievements_project_id'), 'achievements', ['project_id'], unique=False)
    op.create_index(op.f('ix_achievements_work_experience_id'), 'achievements', ['work_experience_id'], unique=False)
    op.drop_constraint(op.f('achievements_workspace_id_fkey'), 'achievements', type_='foreignkey')
    op.drop_constraint(op.f('achievements_user_id_fkey'), 'achievements', type_='foreignkey')
    op.create_foreign_key(None, 'achievements', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'achievements', 'work_experiences', ['work_experience_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'achievements', 'career_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('achievements', 'technical_points_json')
    op.drop_column('achievements', 'interview_points_json')
    op.drop_column('achievements', 'challenges_json')
    op.drop_column('achievements', 'workspace_id')
    op.drop_column('achievements', 'tags_json')
    op.drop_column('achievements', 'solutions_json')
    op.drop_column('achievements', 'metrics_json')
    op.drop_column('achievements', 'user_id')
    op.drop_column('achievements', 'parsed_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('parsed_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('achievements', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('achievements', sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('achievements', sa.Column('solutions_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('achievements', sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('achievements', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('achievements', sa.Column('challenges_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('achievements', sa.Column('interview_points_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('achievements', sa.Column('technical_points_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.create_foreign_key(op.f('achievements_user_id_fkey'), 'achievements', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('achievements_workspace_id_fkey'), 'achievements', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index(op.f('ix_achievements_work_experience_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_project_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_profile_id'), table_name='achievements')
    op.create_index(op.f('ix_achievements_workspace_id'), 'achievements', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.alter_column('achievements', 'source_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('achievements', 'date_occurred')
    op.drop_column('achievements', 'status')
    op.drop_column('achievements', 'tags')
    op.drop_column('achievements', 'parsed_data')
    op.drop_column('achievements', 'work_experience_id')
    op.drop_column('achievements', 'project_id')
    op.drop_column('achievements', 'profile_id')
    op.create_table('candidate_profiles',
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('headline', sa.VARCHAR(length=256), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('exit_story', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('superpowers_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('proof_points_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('compensation_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('location_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('preferences_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('constraints_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('contact_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('candidate_profiles_user_id_fkey')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('candidate_profiles_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('candidate_profiles_pkey'))
    )
    op.create_index(op.f('ix_candidate_profiles_workspace_id'), 'candidate_profiles', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=False)
    op.drop_index(op.f('ix_projects_work_experience_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_profile_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_work_experiences_profile_id'), table_name='work_experiences')
    op.drop_table('work_experiences')
    op.drop_index(op.f('ix_career_profiles_workspace_id'), table_name='career_profiles')
    op.drop_index(op.f('ix_career_profiles_user_id'), table_name='career_profiles')
    op.drop_table('career_profiles')
    # ### end Alembic commands ###
