"""initial_schema

Revision ID: dc1046711b25
Revises: 
Create Date: 2026-04-12 15:37:23.072811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc1046711b25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_owner_user_id'), 'workspaces', ['owner_user_id'], unique=False)
    op.create_table('achievements',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('technical_points_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('challenges_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('solutions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interview_points_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.create_index(op.f('ix_achievements_workspace_id'), 'achievements', ['workspace_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_ref_id', sa.UUID(), nullable=True),
    sa.Column('input_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explainability_notes', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_workspace_id'), 'agent_runs', ['workspace_id'], unique=False)
    op.create_table('jd_snapshots',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('raw_jd', sa.Text(), nullable=True),
    sa.Column('parsed_role_name', sa.String(length=256), nullable=True),
    sa.Column('parsed_keywords_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_required_skills_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_bonus_items_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_style_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_snapshots_user_id'), 'jd_snapshots', ['user_id'], unique=False)
    op.create_index(op.f('ix_jd_snapshots_workspace_id'), 'jd_snapshots', ['workspace_id'], unique=False)
    op.create_table('skill_entities',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('proficiency_level', sa.String(length=32), nullable=True),
    sa.Column('evidence_strength', sa.Float(), nullable=False),
    sa.Column('evidence_refs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_entities_user_id'), 'skill_entities', ['user_id'], unique=False)
    op.create_index(op.f('ix_skill_entities_workspace_id'), 'skill_entities', ['workspace_id'], unique=False)
    op.create_table('target_roles',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=256), nullable=False),
    sa.Column('role_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_skills_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bonus_skills_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_jd_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_roles_user_id'), 'target_roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_target_roles_workspace_id'), 'target_roles', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('achievement_role_matches',
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('target_role_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievement_role_matches_achievement_id'), 'achievement_role_matches', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_achievement_role_matches_target_role_id'), 'achievement_role_matches', ['target_role_id'], unique=False)
    op.create_table('gap_items',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_role_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=256), nullable=False),
    sa.Column('gap_type', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.Text(), nullable=True),
    sa.Column('target_state', sa.Text(), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('improvement_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gap_items_target_role_id'), 'gap_items', ['target_role_id'], unique=False)
    op.create_index(op.f('ix_gap_items_user_id'), 'gap_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_gap_items_workspace_id'), 'gap_items', ['workspace_id'], unique=False)
    op.create_table('resumes',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_role_id', sa.UUID(), nullable=True),
    sa.Column('resume_name', sa.String(length=256), nullable=False),
    sa.Column('resume_type', sa.String(length=32), nullable=False),
    sa.Column('parent_resume_id', sa.UUID(), nullable=True),
    sa.Column('current_version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_target_role_id'), 'resumes', ['target_role_id'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_index(op.f('ix_resumes_workspace_id'), 'resumes', ['workspace_id'], unique=False)
    op.create_table('role_capabilities',
    sa.Column('target_role_id', sa.UUID(), nullable=False),
    sa.Column('core_capabilities_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('secondary_capabilities_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bonus_capabilities_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('project_requirements_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_capabilities_target_role_id'), 'role_capabilities', ['target_role_id'], unique=False)
    op.create_table('jd_resume_tasks',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jd_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('base_resume_id', sa.UUID(), nullable=True),
    sa.Column('generated_resume_id', sa.UUID(), nullable=True),
    sa.Column('ability_match_score', sa.Float(), nullable=False),
    sa.Column('resume_match_score', sa.Float(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=32), nullable=False),
    sa.Column('missing_items_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('optimization_notes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['base_resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['generated_resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['jd_snapshot_id'], ['jd_snapshots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_resume_tasks_jd_snapshot_id'), 'jd_resume_tasks', ['jd_snapshot_id'], unique=False)
    op.create_index(op.f('ix_jd_resume_tasks_user_id'), 'jd_resume_tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_jd_resume_tasks_workspace_id'), 'jd_resume_tasks', ['workspace_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_ref_id', sa.UUID(), nullable=True),
    sa.Column('summary_note', sa.Text(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    op.create_table('update_suggestions',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('suggestion_type', sa.String(length=32), nullable=False),
    sa.Column('target_role_id', sa.UUID(), nullable=True),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_ref_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('impact_score_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_update_suggestions_user_id'), 'update_suggestions', ['user_id'], unique=False)
    op.create_index(op.f('ix_update_suggestions_workspace_id'), 'update_suggestions', ['workspace_id'], unique=False)
    op.create_table('achievement_resume_links',
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('resume_version_id', sa.UUID(), nullable=True),
    sa.Column('applied_section', sa.String(length=128), nullable=True),
    sa.Column('applied_mode', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievement_resume_links_achievement_id'), 'achievement_resume_links', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_achievement_resume_links_resume_id'), 'achievement_resume_links', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_achievement_resume_links_resume_id'), table_name='achievement_resume_links')
    op.drop_index(op.f('ix_achievement_resume_links_achievement_id'), table_name='achievement_resume_links')
    op.drop_table('achievement_resume_links')
    op.drop_index(op.f('ix_update_suggestions_workspace_id'), table_name='update_suggestions')
    op.drop_index(op.f('ix_update_suggestions_user_id'), table_name='update_suggestions')
    op.drop_table('update_suggestions')
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_jd_resume_tasks_workspace_id'), table_name='jd_resume_tasks')
    op.drop_index(op.f('ix_jd_resume_tasks_user_id'), table_name='jd_resume_tasks')
    op.drop_index(op.f('ix_jd_resume_tasks_jd_snapshot_id'), table_name='jd_resume_tasks')
    op.drop_table('jd_resume_tasks')
    op.drop_index(op.f('ix_role_capabilities_target_role_id'), table_name='role_capabilities')
    op.drop_table('role_capabilities')
    op.drop_index(op.f('ix_resumes_workspace_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_target_role_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_gap_items_workspace_id'), table_name='gap_items')
    op.drop_index(op.f('ix_gap_items_user_id'), table_name='gap_items')
    op.drop_index(op.f('ix_gap_items_target_role_id'), table_name='gap_items')
    op.drop_table('gap_items')
    op.drop_index(op.f('ix_achievement_role_matches_target_role_id'), table_name='achievement_role_matches')
    op.drop_index(op.f('ix_achievement_role_matches_achievement_id'), table_name='achievement_role_matches')
    op.drop_table('achievement_role_matches')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_target_roles_workspace_id'), table_name='target_roles')
    op.drop_index(op.f('ix_target_roles_user_id'), table_name='target_roles')
    op.drop_table('target_roles')
    op.drop_index(op.f('ix_skill_entities_workspace_id'), table_name='skill_entities')
    op.drop_index(op.f('ix_skill_entities_user_id'), table_name='skill_entities')
    op.drop_table('skill_entities')
    op.drop_index(op.f('ix_jd_snapshots_workspace_id'), table_name='jd_snapshots')
    op.drop_index(op.f('ix_jd_snapshots_user_id'), table_name='jd_snapshots')
    op.drop_table('jd_snapshots')
    op.drop_index(op.f('ix_agent_runs_workspace_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_achievements_workspace_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_workspaces_owner_user_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
